[package]
name = "keccak-rs"
version = "0.1.0"
edition = "2024"

[dependencies]

[dev-dependencies]
criterion = { version = "0.7", features = ["html_reports"] }
hex = "0.4"

[[bench]]
name = "keccak_bench"
harness = false